name: Advent of Code 2025 in Rust 

on:
  push:
    branches: [ "main" ]
    paths:
      - "2025/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "2025/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install nightly toolchain
      run: rustup toolchain install nightly
    - name: Build
      run: cargo build --release --bin aoc2025
    - name: Run tests
      run: cargo +nightly test --bin aoc2025 -- -Z unstable-options --report-time

